### ISSUE TITLE
can not be loaded in 1.20.5-6

### ISSUE THREAD

**Issue by Darwin1546** [bradleyq/light_painter#10]
```
[05:00:41] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at auv.a(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
	at bpm.d(SourceFile:162) ~[minecraft-1.20.6-client.jar:?]
	at bpq.d(SourceFile:23) ~[minecraft-1.20.6-client.jar:?]
	at bpm.A(SourceFile:136) ~[minecraft-1.20.6-client.jar:?]
	at bpm.bA(SourceFile:121) ~[minecraft-1.20.6-client.jar:?]
	at ffh.c(SourceFile:1275) [minecraft-1.20.6-client.jar:?]
	at ffh.f(SourceFile:888) [minecraft-1.20.6-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:265) [minecraft-1.20.6-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at gdj.c(SourceFile:543) [minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: ali: Invalid shaders/core/rendertype_item_entity_translucent_cull.json: Couldn't compile vertex program (file/light, rendertype_item_entity_translucent_cull) : 0(39) : error C1102: incompatible type for parameter #1 ("pos.21")
0(39) : error C7623: implicit narrowing of type from "vec3" to "int"
0(39) : error C1104: too many parameters in function call
	at ali.a(SourceFile:48) ~[minecraft-1.20.6-client.jar:?]
	at gee.<init>(SourceFile:176) ~[minecraft-1.20.6-client.jar:?]
	at gdj.c(SourceFile:500) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Couldn't compile vertex program (file/light, rendertype_item_entity_translucent_cull) : 0(39) : error C1102: incompatible type for parameter #1 ("pos.21")
0(39) : error C7623: implicit narrowing of type from "vec3" to "int"
0(39) : error C1104: too many parameters in function call
	at ezo.b(SourceFile:69) ~[minecraft-1.20.6-client.jar:?]
	at ezo.a(SourceFile:51) ~[minecraft-1.20.6-client.jar:?]
	at gee.a(SourceFile:214) ~[minecraft-1.20.6-client.jar:?]
	at gee.<init>(SourceFile:161) ~[minecraft-1.20.6-client.jar:?]
	at gdj.c(SourceFile:500) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:421) ~[minecraft-1.20.6-client.jar:?]
	at gdj$1.a(SourceFile:398) ~[minecraft-1.20.6-client.jar:?]
	at auu.a(SourceFile:13) ~[minecraft-1.20.6-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
```

**Comment by bradleyq** [comment]
resolved. closed.
